### PR TITLE
ShiftRegister -> Pipe

### PR DESCRIPTION
**Pull request by donggyukim**
@ccelio I just want to let you know I'm testing this.

### CODE REVIEW

**Comment by donggyukim** [comment]
ISA tests are successful with this change.

**Comment by ccelio** [comment]
Great.  Hopefully Linux will boot now. :D (fingers crossed). I'll leave this unmerged until we verify everything works with an up-to-date chisel. (I don't want a boom commit that doesn't fully work with any chisel version).

**Comment by aswaterman** [comment]
Sorry again, this was a real screw-up on the chisel side.

**Comment by ccelio** [comment]
@aswaterman Thanks, it's understandable and from a few months ago, so I realize we've been getting better and better at this in the mean time.

**Comment by donggyukim** [comment]
Now, boom can boot linux!
@ccelio I totally agree. We may want to wait until ucb-bar/chisel3#530 is merged, and exhaustively test this with various configs (I only tested SmallBOOMConfig with no branch predictor)

**Pull request closed without merging**
