### PR TITLE
[ren] Check register type matches for bypassed allocations

### PR DESCRIPTION
**Pull request by jerryz123**
**Related issue**: 

**Type of change**: bug fix

### CODE REVIEW

**Review by bkorpan — COMMENTED** [review]
Shouldn't need to do this afaik, has this triggered a bug?

**Comment by jerryz123** [comment]
This triggered a bug. I don't see where the bypass bsy bit is gated by register type?
There was a fcvt instruction which was having prs2_bsy set, I assume because if the register type were RT_X it would use the integer rename busy output

**Comment by bkorpan** [comment]
I think I see the problem, it should do the busy bit selection differently.

**Comment by jerryz123** [comment]
If you have a more correct solution I'm happy to use that one.

**Comment by bkorpan** [comment]
Try #374

**Pull request closed without merging**
