### PR TITLE
update rob_fflags

### PR DESCRIPTION
**Pull request by joonho3020**
**Related issue**: 

**Type of change**: bug fix | new feature | other enhancement

Take the `rob_fflags` out of the for loop. This is required to generate certain FireSim annotations regarding multi-ported register files.

**Impact**: no rtl change | rtl refactoring | new rtl | unknown
no rtl change

**Development Phase**: proposal |  implementation

**Release Notes**

### CODE REVIEW

**Comment by jerryz123** [comment]
Can you just convert it from a Mem to a Reg? It should be the same in this case

**Comment by joonho3020** [comment]
Sure, I'll check first if I can build a bitstream off of the Reg version first though.

**Comment by joonho3020** [comment]
This reg is a bit flaky when doing the multi-threading stuff in firesim lol

**Comment by joonho3020** [comment]
Done!

**Review by jerryz123 — APPROVED** [review]

**Pull request merged**
