### PR TITLE
Fetch Buffer Partial Dequeue

### PR DESCRIPTION
**Pull request by bkorpan**
Let the new fetch buffer perform partial dequeues.

### CODE REVIEW

**Comment by jerryz123** [comment]
Do the rob changes break with the old fetchbuffer

**Comment by bkorpan** [comment]
> Do the rob changes break with the old fetchbuffer

No reason they should.

**Comment by jerryz123** [comment]
The modifications to the rob pointer lsb tracking are compatible with both?

**Comment by bkorpan** [comment]
> The modifications to the rob pointer lsb tracking are compatible with both?

Yeah, they should be. I haven't tested extensively.

**Review by abejgonzalez — APPROVED** [review]

**Pull request merged**
