### PR TITLE
BOOM Chisel3 update

### PR DESCRIPTION
**Pull request by abejgonzalez**
This is porting the BOOM codebase to use proper Chisel3 syntax.

Tested with run-asm-tests, run-bmark-tests on SmallBoomConfig and BoomConfig.

Note: RocketChip although using the "import Chisel._" Chisel2 import, is actually using Chisel3 compatibility mode.

### CODE REVIEW

**Comment by abejgonzalez** [comment]
Addresses #120

**Comment by jerryz123** [comment]
LGTM, I think we should just verify Linux on FireSim, and then we can merge

**Comment by sagark** [comment]
If you guys are doing that, can you also PR the bumped BOOM to FireSim dev branch and share the updated fpga images in FireSim?

**Comment by jerryz123** [comment]
Let's merge this, merge the PMP stuff, then bump

**Comment by jackkoenig** [comment]
I would suggest generating a few BOOM configs and then using LEC to prove that this doesn't change the functionality, just to check for unexpected changes in semantics. There aren't supposed to be many but there are a few (in particular, in compatibility mode `:=` is bidirectional, it is monodirectioned in `import chisel3._`)

**Comment by abejgonzalez** [comment]
Chisel3 port allows Linux to boot in FireSim (fireboom-singlecore-nic-ddr3-llc4mb).

Additionally, there are changes in the commits to address := by switching it to a bulk connection <>. Or connecting individual components together.
> (in particular, in compatibility mode `:=` is bidirectional, it is monodirectioned in `import chisel3._`)

In the processes of running LEC checks.

**Comment by abejgonzalez** [comment]
LEC using Formality passes on module BoomCore for both the SmallBoomConfig and default BoomConfig. Any final concerns or comments? Or I will go ahead and merge!

**Comment by jerryz123** [comment]
Seems good to me, what was the issue with only 49% equivalence you were seeing earlier?

**Comment by abejgonzalez** [comment]
One thing, was that I was getting a SIGFPE error when running on BoomTile so I wasn't able to get matching results when comparing that to each other. For BoomCore, after running the tool to ignore "signed to unsigned assignment", I also didn't see the 49% anymore. I dont remember exactly the steps that were taken to resolve the issue since I was trying multiple different things but it looks like things are equivalent with mainly unread points (signals that dont drive anything) not being compared. Let me see if I can recreate it.

**Comment by abejgonzalez** [comment]
So it looks like the 49% was gotten from the matching done on BoomTile for BoomConfig. However, I am not able to diagnose the issue due to the crashing after this point. Looking at the BoomTile code changes the only main difference is the additions of the DontCares (and these signals are not being assigned in the rest of the tile). So I think it is safe to assume it is fine.

**Comment by jerryz123** [comment]
Yeah it's fine, I was just curious what might be causing the divergence

**Comment by abejgonzalez** [comment]
Its seems to be from the BoomTile side but with Formality crashing I can't get more info out. :(

**Pull request merged**
